<a href="https://colab.research.google.com/github/ghowtham12/task-7/blob/main/US_Forensic_Science_Services_Data_KNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import numpy as np
import pandas as pd
df = pd.read_csv('/content/glass.data', names =['Id number','refractive index','Sodium','Magnesium','Aluminum','Silicon','Potassium',' Calcium','Barium','Iron','Type of glass' ])
df

Id number  refractive index  Sodium  Magnesium  Aluminum  Silicon  \
0            1           1.52101   13.64       4.49      1.10    71.78   
1            2           1.51761   13.89       3.60      1.36    72.73   
2            3           1.51618   13.53       3.55      1.54    72.99   
3            4           1.51766   13.21       3.69      1.29    72.61   
4            5           1.51742   13.27       3.62      1.24    73.08   
..         ...               ...     ...        ...       ...      ...   
209        210           1.51623   14.14       0.00      2.88    72.61   
210        211           1.51685   14.92       0.00      1.99    73.06   
211        212           1.52065   14.36       0.00      2.02    73.42   
212        213           1.51651   14.38       0.00      1.94    73.61   
213        214           1.51711   14.23       0.00      2.08    73.36   

     Potassium   Calcium  Barium  Iron  Type of glass  
0         0.06      8.75    0.00   0.0              1  
1         0.48      7.83    0.00   0.0              1  
2         0.39      7.78    0.00   0.0              1  
3         0.57      8.22    0.00   0.0              1  
4         0.55      8.07    0.00   0.0              1  
..         ...       ...     ...   ...            ...  
209       0.08      9.18    1.06   0.0              7  
210       0.00      8.40    1.59   0.0              7  
211       0.00      8.44    1.64   0.0              7  
212       0.00      8.48    1.57   0.0              7  
213       0.00      8.62    1.67   0.0              7  

[214 rows x 11 columns]

In [9]:
df.isnull().sum()

Id number           0
refractive index    0
Sodium              0
Magnesium           0
Aluminum            0
Silicon             0
Potassium           0
 Calcium            0
Barium              0
Iron                0
Type of glass       0
dtype: int64

In [10]:
df.describe()

Id number  refractive index      Sodium   Magnesium    Aluminum  \
count  214.000000        214.000000  214.000000  214.000000  214.000000   
mean   107.500000          1.518365   13.407850    2.684533    1.444907   
std     61.920648          0.003037    0.816604    1.442408    0.499270   
min      1.000000          1.511150   10.730000    0.000000    0.290000   
25%     54.250000          1.516522   12.907500    2.115000    1.190000   
50%    107.500000          1.517680   13.300000    3.480000    1.360000   
75%    160.750000          1.519157   13.825000    3.600000    1.630000   
max    214.000000          1.533930   17.380000    4.490000    3.500000   

          Silicon   Potassium     Calcium      Barium        Iron  \
count  214.000000  214.000000  214.000000  214.000000  214.000000   
mean    72.650935    0.497056    8.956963    0.175047    0.057009   
std      0.774546    0.652192    1.423153    0.497219    0.097439   
min     69.810000    0.000000    5.430000    0.000000    0.000000   
25%     72.280000    0.122500    8.240000    0.000000    0.000000   
50%     72.790000    0.555000    8.600000    0.000000    0.000000   
75%     73.087500    0.610000    9.172500    0.000000    0.100000   
max     75.410000    6.210000   16.190000    3.150000    0.510000   

       Type of glass  
count     214.000000  
mean        2.780374  
std         2.103739  
min         1.000000  
25%         1.000000  
50%         2.000000  
75%         3.000000  
max         7.000000

In [11]:
df.corr()

Id number  refractive index    Sodium  Magnesium  Aluminum  \
Id number          1.000000         -0.072209  0.375722  -0.650328  0.490113   
refractive index  -0.072209          1.000000 -0.191885  -0.122274 -0.407326   
Sodium             0.375722         -0.191885  1.000000  -0.273732  0.156794   
Magnesium         -0.650328         -0.122274 -0.273732   1.000000 -0.481799   
Aluminum           0.490113         -0.407326  0.156794  -0.481799  1.000000   
Silicon            0.061232         -0.542052 -0.069809  -0.165927 -0.005524   
Potassium          0.003149         -0.289833 -0.266087   0.005396  0.325958   
 Calcium           0.090800          0.810403 -0.275442  -0.443750 -0.259592   
Barium             0.451001         -0.000386  0.326603  -0.492262  0.479404   
Iron              -0.072794          0.143010 -0.241346   0.083060 -0.074402   
Type of glass      0.877357         -0.164237  0.502898  -0.744993  0.598829   

                   Silicon  Potassium   Calcium    Barium      Iron  \
Id number         0.061232   0.003149  0.090800  0.451001 -0.072794   
refractive index -0.542052  -0.289833  0.810403 -0.000386  0.143010   
Sodium           -0.069809  -0.266087 -0.275442  0.326603 -0.241346   
Magnesium        -0.165927   0.005396 -0.443750 -0.492262  0.083060   
Aluminum         -0.005524   0.325958 -0.259592  0.479404 -0.074402   
Silicon           1.000000  -0.193331 -0.208732 -0.102151 -0.094201   
Potassium        -0.193331   1.000000 -0.317836 -0.042618 -0.007719   
 Calcium         -0.208732  -0.317836  1.000000 -0.112841  0.124968   
Barium           -0.102151  -0.042618 -0.112841  1.000000 -0.058692   
Iron             -0.094201  -0.007719  0.124968 -0.058692  1.000000   
Type of glass     0.151565  -0.010054  0.000952  0.575161 -0.188278   

                  Type of glass  
Id number              0.877357  
refractive index      -0.164237  
Sodium                 0.502898  
Magnesium             -0.744993  
Aluminum               0.598829  
Silicon                0.151565  
Potassium             -0.010054  
 Calcium               0.000952  
Barium                 0.575161  
Iron                  -0.188278  
Type of glass          1.000000

In [12]:
x = df[['Sodium',	'Magnesium','Aluminum',	'Barium']].values
y = df['Type of glass'].values

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2)

In [13]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
scaled_x_train = sc.fit_transform(x_train)
scaled_x_test = sc.transform(x_test)

In [14]:
from sklearn.model_selection import cross_val_score
from sklearn.neighbors import KNeighborsClassifier
for i in [1,2,3,4,5,6,7,8,9,10]:
  knn = KNeighborsClassifier(i)
  knn.fit(scaled_x_train,y_train)
  print('k-value :',i, 'trainscore :', knn.score(scaled_x_train,y_train), 'score =', np.mean(cross_val_score(knn,x_train, y_train, cv =10))) 

/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_split.py:676: UserWarning: The least populated class in y has only 7 members, which is less than n_splits=10.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_split.py:676: UserWarning: The least populated class in y has only 7 members, which is less than n_splits=10.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_split.py:676: UserWarning: The least populated class in y has only 7 members, which is less than n_splits=10.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_split.py:676: UserWarning: The least populated class in y has only 7 members, which is less than n_splits=10.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_split.py:676: UserWarning: The least populated class in y has only 7 members, which is less than n_splits=10.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklear

k-value : 1 trainscore : 1.0 score = 0.6316993464052288
k-value : 2 trainscore : 0.8421052631578947 score = 0.6254901960784314
k-value : 3 trainscore : 0.7894736842105263 score = 0.6375816993464054
k-value : 4 trainscore : 0.7602339181286549 score = 0.6607843137254903
k-value : 5 trainscore : 0.7426900584795322 score = 0.6486928104575165
k-value : 6 trainscore : 0.7368421052631579 score = 0.6372549019607842
k-value : 7 trainscore : 0.7368421052631579 score = 0.6431372549019608
k-value : 8 trainscore : 0.7076023391812866 score = 0.6310457516339869
k-value : 9 trainscore : 0.7017543859649122 score = 0.6251633986928105
k-value : 10 trainscore : 0.6900584795321637 score = 0.6369281045751635


/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_split.py:676: UserWarning: The least populated class in y has only 7 members, which is less than n_splits=10.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_split.py:676: UserWarning: The least populated class in y has only 7 members, which is less than n_splits=10.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_split.py:676: UserWarning: The least populated class in y has only 7 members, which is less than n_splits=10.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_split.py:676: UserWarning: The least populated class in y has only 7 members, which is less than n_splits=10.
  warnings.warn(


In [18]:
knn = KNeighborsClassifier(4)
knn.fit(scaled_x_train,y_train)
y_pred= knn.predict(scaled_x_test)
y_pred

array([7, 2, 2, 7, 1, 1, 1, 2, 1, 1, 2, 2, 1, 2, 2, 1, 7, 6, 7, 1, 1, 2,
       5, 1, 2, 1, 2, 7, 1, 2, 2, 1, 1, 7, 1, 2, 7, 1, 5, 2, 1, 2, 3])

In [19]:
from sklearn.metrics import accuracy_score,roc_auc_score,classification_report,confusion_matrix,plot_confusion_matrix,plot_roc_curve
cm=confusion_matrix(y_test,y_pred)
print("confusion matrix : ",cm)

confusion matrix :  [[12  2  1  0  0  0]
 [ 3  9  0  0  0  0]
 [ 2  2  0  0  0  0]
 [ 0  0  0  2  0  0]
 [ 0  1  0  0  1  0]
 [ 0  1  0  0  0  7]]


In [21]:
#manhattan
manh_knn=KNeighborsClassifier(n_neighbors=4,metric="manhattan")
manh_knn.fit(scaled_x_train,y_train)
manh_pred=manh_knn.predict(scaled_x_test)
print(classification_report(y_test,manh_pred))
print("ACCURACY:",accuracy_score(y_test,manh_pred))

              precision    recall  f1-score   support

           1       0.67      0.80      0.73        15
           2       0.57      0.67      0.62        12
           3       0.00      0.00      0.00         4
           5       1.00      1.00      1.00         2
           6       1.00      0.50      0.67         2
           7       1.00      0.88      0.93         8

    accuracy                           0.70        43
   macro avg       0.71      0.64      0.66        43
weighted avg       0.67      0.70      0.68        43

ACCURACY: 0.6976744186046512


In [23]:
seq_knn=KNeighborsClassifier(n_neighbors=6,metric="sqeuclidean")
seq_knn.fit(scaled_x_train,y_train)
seq_pred=seq_knn.predict(scaled_x_test)
print(classification_report(y_test,seq_pred))
print("ACCURACY:",accuracy_score(y_test,seq_pred))

              precision    recall  f1-score   support

           1       0.74      0.93      0.82        15
           2       0.71      0.83      0.77        12
           3       0.00      0.00      0.00         4
           5       1.00      1.00      1.00         2
           6       1.00      0.50      0.67         2
           7       1.00      0.88      0.93         8

    accuracy                           0.79        43
   macro avg       0.74      0.69      0.70        43
weighted avg       0.74      0.79      0.75        43

ACCURACY: 0.7906976744186046


/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
